management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        circuitbreakers:
            enabled: true
resilience4j:
    circuitbreaker:
        instances:
            peopleEndpointCircuitBreaker:
                failureRateThreshold: 50
                slowCallRateThreshold: 50
                slowCallDurationThreshold: 2s
                waitDurationInOpenState: 5s
                automaticTransitionFromOpenToHalfOpenEnabled: true
                permittedNumberOfCallsInHalfOpenState: 3
                minimumNumberOfCalls: 5
                slidingWindowSize: 10
                registerHealthIndicator: true
            recordExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
spring:
    application:
        name: spring.boot.resilience4j
swapiConnector:
    baseURL: https://swapi.dev
